name: Publish Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tomastokamrazek/http-proxy-to-socks
      
      - name: Docker Build And Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
